In [2]:
import numpy as np
import torch

In [3]:
test = np.load("data/FSC147_384_V2/gt_density_map_adaptive_384_VarV2/2.npy")
test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(384, 633), dtype=float32)

In [20]:
a = torch.tensor([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                  [[11,22,33],
                  [44,55,66],
                  [77,88,99]]])

a.shape

x1 = [0,int(0)]
x2 = [2,1]

a[:, x1[0]:x2[0]+1, x1[1]:x2[1]+1]

tensor([[[ 1,  2],
         [ 4,  5],
         [ 7,  8]],

        [[11, 22],
         [44, 55],
         [77, 88]]])

In [3]:
# https://pytorch.org/hub/pytorch_vision_resnet/
model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)

Downloading: "https://github.com/pytorch/vision/zipball/v0.10.0" to /Users/andrewluther/.cache/torch/hub/v0.10.0.zip
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /Users/andrewluther/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100.0%


In [14]:
import numpy as np
import torch

# ref https://stackoverflow.com/questions/49768306/pytorch-tensor-to-numpy-array


a = torch.tensor([[1,2,3],
             [4,5,6]]).detach().numpy()

b = torch.tensor([[-1,2,3],
             [4,-6,6]]).detach().numpy()

correlation = torch.from_numpy(np.corrcoef(a, b))
correlation

tensor([[ 1.0000,  1.0000,  0.9608,  0.1555],
        [ 1.0000,  1.0000,  0.9608,  0.1555],
        [ 0.9608,  0.9608,  1.0000, -0.1245],
        [ 0.1555,  0.1555, -0.1245,  1.0000]], dtype=torch.float64)

## Testing the correlation map stuff

In [25]:
# Testing to make sure conv2d does what we think it does
import torch
import torch.nn.functional as F

image = torch.tensor(
        [[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],],
         [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],]]]
         )

kernel = torch.tensor(
                    [[[[1,0,0],
                    [1,0,0], 
                    [1,0,0], ],
                    [[1,0,0],
                    [1,0,0], 
                    [1,0,0], ]],
                    [[[0,0,0],
                    [0,0,0], 
                    [0,0,0], ],
                    [[0,0,0],
                    [0,0,0], 
                    [0,0,0], ]]])

print(image.shape)
print(kernel.shape)

correlation_map = F.conv2d(image, kernel, stride=1, padding=1)

correlation_map


torch.Size([1, 2, 5, 5])
torch.Size([2, 2, 3, 3])


tensor([[[[0, 6, 6, 6, 6],
          [0, 9, 9, 9, 9],
          [0, 9, 9, 9, 9],
          [0, 9, 9, 9, 9],
          [0, 6, 6, 6, 6]],

         [[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]])

In [34]:
import torch

torch.signal.windows.gaussian(6).view((2,3))

tensor([[0.0439, 0.3247, 0.8825],
        [0.8825, 0.3247, 0.0439]])